import { useEffect, useState } from 'react';
import { Bot, Play, Search, Database, Globe2, CheckCircle2, AlertCircle, RefreshCw, ArrowRight, Sparkles } from 'lucide-react';
import { api } from '../api.js';
import { StatusBadge } from '../components/StatusBadge.jsx';
export function AgentView({ openIndicator, go, refreshKey, onChanged }) {
  const [data,setData]=useState(null); const [running,setRunning]=useState(false); const [msg,setMsg]=useState('');
  const load=()=>api.agentStatus().then(setData).catch(e=>setMsg(e.message)); useEffect(load,[refreshKey]);
  const run=async()=>{setRunning(true);setMsg('');try{const r=await api.runAgent();setMsg(r.summary);await load();onChanged?.();}catch(e){setMsg(e.message)}finally{setRunning(false)}};
  return <div className="page-content"><section className="agent-hero"><div className="agent-hero-icon"><Bot size={29}/><span/></div><div><span className="eyebrow">Pesquisa assistida por IA</span><h1>Agente de Indicadores</h1><p>Investiga fontes públicas, cria descobertas e mantém a base oficial protegida. Nada entra como dado oficial sem validação humana.</p></div><button className="primary-btn agent-run" disabled={running||!data?.configured} onClick={run}>{running?<RefreshCw className="spin" size={18}/>:<Play size={17}/>} {running?'Pesquisando...':'Executar pesquisa agora'}</button></section>
    {msg&&<div className={`inline-message ${/não configurado|erro/i.test(msg)?'error':''}`}>{msg}</div>}
    <div className="agent-status-strip"><div><span className={`dot ${data?.configured?'online':''}`}/><p><strong>{data?.configured?'Agente configurado':'Agente sem chave de pesquisa'}</strong><small>{data?.provider||'Carregando...'}</small></p></div><div><Globe2/><p><strong>{data?.lastRun?.indicatorsChecked||0}</strong><small>analisados na última execução</small></p></div><div><Database/><p><strong>{data?.lastRun?.candidatesCreated||0}</strong><small>novas descobertas</small></p></div><div><CheckCircle2/><p><strong>{data?.newFindings||0}</strong><small>aguardando revisão</small></p></div></div>
    {!data?.configured&&<div className="configuration-callout"><AlertCircle size={20}/><div><strong>Para ativar a pesquisa real</strong><p>Configure <code>OPENAI_API_KEY</code> (recomendado) ou <code>TAVILY_API_KEY</code> no servidor. Sem chave, o sistema mantém todos os indicadores e fluxos de validação funcionando, mas não finge que pesquisou.</p></div></div>}
    <div className="agent-workbench"><section className="queue-panel"><div className="workbench-title"><span>Fila de investigação</span><b>{data?.queue?.length||0}</b></div>{data?.queue?.map((i,idx)=><button key={i.id} onClick={()=>openIndicator(i.id)} className={idx===0?'selected':''}><div className="queue-code">{i.code}</div><span><strong>{i.name}</strong><small>ISO {i.standard.code} · prioridade {i.priority}</small></span><StatusBadge status={i.status}/></button>)}</section>
      <section className="investigation-panel"><div className="investigation-top"><div><span className="eyebrow">Como o agente trabalha</span><h3>Investigação segura e rastreável</h3></div><Sparkles size={21}/></div><div className="agent-steps">{[['01','Interpreta o indicador','Separa numerador, denominador, unidade e ano necessário.'],['02','Prioriza fontes oficiais','Prefeitura, SAAE, IBGE, SINISA, DATASUS, INEP e outras bases públicas.'],['03','Cria uma descoberta','Valor, fonte, URL, trecho de evidência, ano e nível de confiança.'],['04','Não altera a base','A descoberta fica na caixa de entrada até você aceitar e validar.']].map(([n,t,d])=><div key={n}><b>{n}</b><span><strong>{t}</strong><small>{d}</small></span></div>)}</div><div className="flow-diagram"><span><Search/> Pesquisa</span><i>→</i><span><Database/> Descoberta</span><i>→</i><span><CheckCircle2/> Validação humana</span></div></section>
      <section className="runs-panel"><div className="workbench-title"><span>Execuções recentes</span></div>{data?.runs?.slice(0,7).map(r=><div className="run-row" key={r.id}><span className={`run-dot ${r.status.toLowerCase()}`}/><div><strong>{new Date(r.startedAt).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}</strong><small>{r.summary||r.status}</small></div><b>{r.candidatesCreated}</b></div>)}<button className="secondary-btn wide" onClick={()=>go('findings')}>Abrir descobertas <ArrowRight size={16}/></button></section></div>
  </div>;
}
