import { useEffect, useState } from 'react';
import { ExternalLink, Check, X, Clock3, ShieldCheck, Search, Inbox } from 'lucide-react';
import { api } from '../api.js';
import { StatusBadge } from '../components/StatusBadge.jsx';
export function FindingsView({ openIndicator, refreshKey, onChanged }) {
  const [data,setData]=useState(null); const [filter,setFilter]=useState('NEW,AWAITING_VALIDATION,DIVERGENCE'); const [busy,setBusy]=useState(''); const [msg,setMsg]=useState('');
  const load=()=>api.findings(filter).then(setData).catch(e=>setMsg(e.message)); useEffect(load,[filter,refreshKey]);
  const act=async(id,type)=>{setBusy(id);setMsg('');try{if(type==='accept')await api.acceptFinding(id);if(type==='reject')await api.rejectFinding(id,prompt('Motivo da rejeição:')||'Rejeitado na revisão');if(type==='later')await api.laterFinding(id);if(type==='validate')await api.validateFinding(id);await load();onChanged?.()}catch(e){setMsg(e.message)}finally{setBusy('')}};
  return <div className="page-content"><section className="page-header findings-header"><div><span className="eyebrow">Caixa de entrada protegida</span><h1>Descobertas do Agente</h1><p>Compare o que já existe com cada nova fonte. Aceitar não é validar: a decisão final continua sendo humana.</p></div><div className="inbox-visual"><Inbox size={27}/><b>{data?.items?.length||0}</b><span>itens nesta visão</span></div></section>{msg&&<div className="inline-message error">{msg}</div>}
    <div className="filter-pills"><button className={filter==='NEW,AWAITING_VALIDATION,DIVERGENCE'?'active':''} onClick={()=>setFilter('NEW,AWAITING_VALIDATION,DIVERGENCE')}>Pendentes</button><button className={filter==='AWAITING_VALIDATION'?'active':''} onClick={()=>setFilter('AWAITING_VALIDATION')}>Aguardando validação</button><button className={filter==='VALIDATED'?'active':''} onClick={()=>setFilter('VALIDATED')}>Validadas</button><button className={filter==='REJECTED'?'active':''} onClick={()=>setFilter('REJECTED')}>Rejeitadas</button><button className={filter===''?'active':''} onClick={()=>setFilter('')}>Todas</button></div>
    <div className="findings-list">{data?.items.map(f=>{const cur=f.indicator.currentValue;const old=f.targetField==='NUMERATOR'?(cur?.numeratorRaw??cur?.numeratorNumber):f.targetField==='DENOMINATOR'?(cur?.denominatorRaw??cur?.denominatorNumber):(cur?.finalRaw??cur?.finalNumber);return <article className="finding-card" key={f.id}><div className="finding-head"><div><span className="code-pill">{f.indicator.code}</span><span>ISO {f.indicator.standard.code}</span><StatusBadge status={f.status}/></div><span className={`confidence confidence-${f.confidenceLevel.toLowerCase()}`}>{f.confidenceScore}% confiança</span></div><h3 onClick={()=>openIndicator(f.indicator.id)}>{f.indicator.name}</h3><div className="finding-compare"><div><small>Dado atual · {f.targetField}</small><strong>{old??'Não localizado'}</strong><span>{f.targetField==='NUMERATOR'?(cur?.numeratorYear||''):(cur?.denominatorYear||'')}</span></div><i>→</i><div className="candidate"><small>Nova descoberta</small><strong>{f.candidateValueRaw||'Fonte candidata'}</strong><span>{f.referenceYear||'ano a confirmar'} {f.unit?`· ${f.unit}`:''}</span></div></div><div className="finding-source"><div><span>Fonte encontrada</span><strong>{f.sourceName}</strong><small>{f.sourceOrganization||f.sourceType||''}</small></div>{f.sourceUrl&&<a href={f.sourceUrl} target="_blank" rel="noreferrer">Ver fonte <ExternalLink size={14}/></a>}</div>{f.evidenceExcerpt&&<blockquote>{f.evidenceExcerpt}</blockquote>}<div className="confidence-reason"><ShieldCheck size={15}/>{f.confidenceReason||'Revisar a evidência antes de usar.'}</div><div className="finding-actions">{f.status==='NEW'&&<><button className="ghost-btn" disabled={busy===f.id} onClick={()=>act(f.id,'reject')}><X size={15}/> Rejeitar</button><button className="ghost-btn" disabled={busy===f.id} onClick={()=>act(f.id,'later')}><Clock3 size={15}/> Investigar depois</button><button className="secondary-btn" disabled={busy===f.id} onClick={()=>act(f.id,'accept')}><Check size={15}/> Aceitar descoberta</button></>}{f.status==='AWAITING_VALIDATION'&&<button className="primary-btn" disabled={busy===f.id} onClick={()=>act(f.id,'validate')}><ShieldCheck size={16}/> Validar dado</button>}<button className="text-button" onClick={()=>openIndicator(f.indicator.id)}><Search size={14}/> Abrir indicador</button></div></article>})}</div>
    {!data?.items?.length&&<div className="empty-state"><Inbox/><h3>Nenhuma descoberta nesta fila</h3><p>Quando o agente encontrar novas fontes, elas aparecerão aqui antes de qualquer alteração na base oficial.</p></div>}
  </div>;
}
